app:
  name: gopulse-messages
  port: 8080
  read_timeout: 30   
  write_timeout: 30     
  idle_timeout: 120   
  max_header_mb: 1    

database:
  dsn: postgres://postgres:postgres@localhost:5433/gopulse_messages?sslmode=disable

redis:
  addr: localhost:6379
  password: ""
  db: 0

webhook:
  host: https://webhook.site
  path: 2c81363d-4f2f-4e0a-975e-73e883e7aeda
